In [71]:
import numpy as np
a = np.arange(50,100)
print(a)


[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [34]:
a = np.array([1,0,6])
b = np.repeat(a,10)
print(b)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 6 6 6 6 6]


In [37]:
a = np.arange(20,32)
b = a.reshape(3,4)
print(b)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [36]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
a = np.zeros((5,5))
print(a)
i = 0
for i in range(5):
    a[i,i] = a[i,i] + (i+1)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [70]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
Sum = np.sum(a)
Sumrow = np.sum(a,axis=0)
Sumcol = np.sum(a,axis=1)
print(Sum)
print(Sumrow)
print(Sumcol)

30
[ 2  4  6  8 10]
[15 15]


In [76]:
#Salary
StephenCurry_S= [9887642,10629213,11370786,12112359,34682500,37457154,40231758,40491877,45780966,48070014]
LebronJames_S = [44474988,41180544,39219566,37436845,35454150,33285709,30963450,22970500,20644400,19067500]
AnthonyDavis_S = [37980720,35361360,32742000,247093019,25434263,23775503,22116750,7070730,5607240,5375760]
JimmyButler_S = [37653300,36016200,34379100,32742000,19841627,18696918,17552209,16407500,2119214,1174080]
LukaDoncic_S = [37096500,10174391,8049360,7683360,6569040,0,0,0,0,0]
GiannisAntetokounmpo_S = [42492492,39344900,27528088,25842697,24157304,22471911,2995410,1953960,1873200,1792560]
JamesHarden_S = [33000000,44310840,44254920,38199000,30570000,28299399,26540100,15719062,14693906,13668750]
NikolaJokic_S = [33047803,31044906,29542010,27504630,25467250,1471382,1358500,1300000,0,0]
DamianLillard_S = [42492492,39344900,31626953,29802321,27977689,26153057,23328425,4236286,3340940,3202920]
TobiasHarris_S = [37633050,35995960,34358850,32742000,14800000,16000000,17200000,16000000,2511432,1630800]
Salary = np.array([StephenCurry_S,LebronJames_S,AnthonyDavis_S,JimmyButler_S,LukaDoncic_S,GiannisAntetokounmpo_S,JamesHarden_S,NikolaJokic_S,DamianLillard_S,TobiasHarris_S])
#Games
StephenCurry_G = [40,64,63,5,69,51,79,79,80,77]
LebronJames_G = [47,56,45,67,55,82,74,76,69,77]
AnthonyDavis_G = [41,40,36,62,56,75,75,61,68,67]
JimmyButler_G = [52,57,52,58,55,10,59,76,67,65]
LukaDoncic_G = [57,65,66,61,72,0,0,0,0,0]
GiannisAntetokounmpo_G = [52,67,61,63,72,75,80,80,81,77]
JamesHarden_G = [48,65,44,68,78,72,81,82,81,73]
NikolaJokic_G = [58,74,72,73,80,75,73,80,0,0]
DamianLillard_G = [53,29,67,66,80,73,75,75,82,82]
TobiasHarris_G = [60,73,62,72,27,55,32,48,82,27]
Games = np.array([StephenCurry_G,LebronJames_G,AnthonyDavis_G,JimmyButler_G,LukaDoncic_G,GiannisAntetokounmpo_G,JamesHarden_G,NikolaJokic_G,DamianLillard_G,TobiasHarris_G])
#Goals
StephenCurry_FG = [394,535,658,33,632,428,675,805,653,652]
LebronJames_FG = [532,640,422,643,558,857,736,737,624,767]
AnthonyDavis_FG = [405,370,301,551,530,780,770,560,642,522]
JimmyButler_FG = [374,398,366,345,344,74,437,570,470,421]
LukaDoncic_FG = [629,641,647,581,506,0,0,0,0,0]
GiannisAntetokounmpo_FG = [574,689,626,685,721,742,656,513,383,173]
JamesHarden_FG = [316,407,342,672,843,651,674,710,645,549]
NikolaJokic_FG = [535,764,732,565,616,504,494,307,0,0]
DamianLillard_FG = [515,222,602,624,681,621,661,618,590,553]
TobiasHarris_FG = [353,493,473,553,187,424,242,320,511,417]
Goals = np.array([StephenCurry_FG,LebronJames_FG,AnthonyDavis_FG,JimmyButler_FG,LukaDoncic_FG,GiannisAntetokounmpo_FG,JamesHarden_FG,NikolaJokic_FG,DamianLillard_FG,TobiasHarris_FG])

SalaryRow = np.sum(Salary,axis=0)
SalaryCol = np.sum(Salary,axis=1)
GamesRow = np.sum(Games,axis=0)
GamesCol = np.sum(Games,axis=1)
GoalsRow = np.sum(Goals,axis=0)
GoalsCol = np.sum(Goals,axis=1)
print(######Salary)
print(SalaryRow)
print(SalaryCol)
print(######Games)
print(GamesRow)
print(GamesCol)
print(######Goals)
print(GoalsRow)
print(GoalsCol)

[355758987 323403214 293071633 491158231 244953823 207611033 182286602
 126149915  96571298  93982384]
[290714269 324697652 442557345 216582148  69572651 190452522 289255977
 150736481 231505983 208872092]
[508 590 568 595 644 568 628 657 610 545]
[607 648 581 551 321 708 692 585 682 538]
[4627 5159 5169 5252 5618 5081 5345 5140 4518 4054]
[5465 6516 5431 3799 3004 5762 5809 4517 5687 3973]
